name: Test
on: [push]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: leafo/gh-actions-lua@v11
        with:
          luaVersion: '5.3.5'

      - name: Test
        run: |
          lua test/test.lua
