name: Typecheck
on: [push]

jobs:
  build:
    name: Typecheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Lua LSP Typecheck
        uses: mrcjkb/lua-typecheck-action@v0
